list: $/vdomah/roles/models/condition/columns.yaml
modelClass: Vdomah\Roles\Models\Condition
title: Conditions
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'vdomah/roles/conditions/update/:id'
